sudo: false

language: node_js

branches:
  only:
    - master

before_install:
  - cd client

cache:
  directories:
    - "node_modules"

env:
  - BACKEND_URL=$BACKEND_URL

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master

notifications:
  email:
    on_failure: change
