sudo: false

language: node_js

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - cd client

cache: yarn

env:
  - BACKEND_URL=$BACKEND_URL

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master

notifications:
  email:
    on_failure: change
