sudo: false

language: node_js

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - cd client

install: yarn --ignore-engines

env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH
    - BACKEND_URL=$BACKEND_URL

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master

notifications:
  email:
    on_failure: change
