version: "3"

services:
  api-service:
    container_name: api-service
    build: .
    environment:
      - MONGO_HOST=mongo-service:27017
      - WAIT_HOSTS=mongo-service:27017
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    ports:
      - 3000:8080
    depends_on:
      - mongo-service
  mongo-service:
    container_name: mongo-service
    image: mongo:3.4.17-jessie
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./mongo-data:/data/db
    expose:
      - "27017"
